image: ubuntu:18.04
 
before_script:
  - ./setup-build-env.sh
 
stages:
  - build
 
compile:
  stage: build
  tags:
    - docker
  script:
    - arduino-cli compile --fqbn esp32:esp32:esp32 -o ignored.bin robot.ino
